### ISSUE TITLE
受益匪浅

### ISSUE THREAD

**Issue by parzulpan** [feiyangqingyun/qtkaifajingyan#1]
刚看完了，谢谢作者，受益匪浅！
(目前考虑新的工作环境吗？我司有招聘需求。

**Comment by maoqin-h** [comment]
最近想在 github上找点qt项目看看，学习下qt， 翻到好东西 谢谢~~

**Comment by xspeed1989** [comment]
20K 的工作岗位很少（成都）

**Comment by Reisen1969** [comment]
良心，几天前作者还更新了

**Comment by feiyangqingyun** [comment]
> 良心，几天前作者还更新了

是的，全部更新了支持Qt4-Qt6

**Comment by sloanyyc** [comment]
这绝对是武林秘籍，九阳神功。
最近弄了个 绿色版的Qt开发环境，欢饮大家体验。
链接: https://pan.baidu.com/s/1Is0XaWuanSsjDeMisiaz2g 提取码: b335 

    用于 Win7/8/10 64位Qt开发调试
    本压缩包180M左右，可用于 Win7/8/10 64位Qt开发调试
    包含Qt5.15.2 Debug Release 除qtwebengine外全部模块
    包含Qt Creator4.5.2 除文档外几乎全部模块
    包含VS2019 X64编译系统，cl.exe nmake.exe等
    包含Windows Kits 8.1调试器 cdb.exe
