### ISSUE TITLE
One more Question about QWebEngine

### ISSUE THREAD

**Issue by Yooi** [feiyangqingyun/qtkaifajingyan#6]
非常感谢分享这么多经验，我最近一直做的项目有一个问题困扰了我很久，没有很好的解决办法

就是QWebEnginePage显示没有chrome那么自然的问题，字体偏小，我在每次UrlChanged时候设置setZoomFactor，1是不能根据屏幕适配，2就是不能统一设置，有没有更好的办法解决呢，

另外QWebEngine如何可以优化加载，改善Profermance

Thanks Bro

**Comment by feiyangqingyun** [comment]
估计悬，能正常打开网页并js交互就行了。
