### ISSUE TITLE
请教 Qt Designer 创建 .ui 运行后，字体和控件都很大？

### ISSUE THREAD

**Issue by XMuli** [feiyangqingyun/qtkaifajingyan#9]
前不久有些坑也踩到了，结果发现在此已被收集 eg 185 的 Bug，甚是感谢，且觉受益匪浅。

再提一个建议给； 200+ 条宝贵的经验，可以按照项目开发阶段，大致分一个类别归类，也便于 Find

----

请教一下博主另一个问题；请教 Qt Designer 创建 .ui 运行后，字体和控件都很大，有无解决方式？
之前使用纯代码书写一个 Widget 界面，其子控件看起来比较小（符合预期）；今准备修改使用 Qt Designer 创建 .ui 来实现，但运行后很大（不符合预期）。 都是同一个显示器，**界面尺寸同样大，子控件也按照设计图**， win10 + 4K 27‘； 放一个对比图，感觉明显。

<img src="https://user-images.githubusercontent.com/33887845/230764825-635d5c13-0da3-45da-859a-f1717bef2ff8.png" width="60%"/>

**Comment by feiyangqingyun** [comment]
可以吧电脑的显示分辨率那边改成100%缩放即可
